text: "welcome back, Admin"
triggers:
  - set role:
    freeInputID: "setRole"
    text: "enter user id"
    cmd_triggers:
      - good: 
        text: "select role"
        triggers:
          - -user:
            cmdID: "delRoleUser"
            ref: -3
          - +user:
            cmdID: "setRoleUser"
            ref: -3
          - -support:
            cmdID: "delRoleSupport"
            ref: -3
          - +support:
            cmdID: "setRoleSupport"
            ref: -3
      - bad:
        text: "no such user"
        ref: -1