text: "welcome back, Admin"
triggers:
  set role:
    input_parse_id: "setRoleUser"
    input_user_id: "setRoleUser"
    input_switch_id: "setRoleUser"
    text: "enter user id"
    triggers:
      -change role; -role; =main; -change lang:
    switch_triggers:
      good:
        text: "select role"
        input_parse_id: "setRoleRole"
        input_user_id: "setRoleRole"
        input_switch_id: "setRoleRole"
        triggers:
          -change role; -role; =main:
        switch_triggers:
          good:
            text: "done"
            ref: -3
          bad:
            text: "something has gone wrong"
            ref: -3
    bad:
        text: "no such user"
        ref: -1