triggers:
  - назад:
      ref: -2
  - главная; /start:
      ref: 0
  - привет:
      cmd_id: "hi"
      text: "привет"
      ref: -1
  - смена языка:
      text: "выберете язык"
      triggers:
        - ru:
            cmd_id: "toRu"
            ref: -2
        - en:
            cmd_id: "toEn"
            ref: -2
        - ua:
            cmd_id: "toUa"
            ref: -2
  - сменить роль; роль:
      ref_id: "changeRole"
      text: "выберите роль"
      triggers:
        - пользователь:
            cmd_id: "changeRoleToUser"
            cmd_triggers:
              - forbidden:
                  text: "у вас нет на это прав"
                  ref: -2
              - allowed:
                  ref: 0
        - админ:
            cmd_id: "changeRoleToAdmin"
            cmd_triggers:
              - forbidden:
                  text: "у вас нет на это прав"
                  ref: -2
              - allowed:
                  ref: 0
        - поддержка:
            cmd_id: "changeRoleToSupport"
            cmd_triggers:
              - forbidden:
                  text: "у вас нет на это прав"
                  ref: -2
              - allowed:
                  ref: 0